### ISSUE TITLE
Sopivilla ikkunan leveyksillä "Fork me on GitHub" -ribbon menee navin linkkien päälle

### ISSUE THREAD

**Issue by terotil** [jannecederberg/koodaustunti.fi#1]
Yritin blogiin ja päädyin tänne GitHub-repoon. :)

**Comment by jannecederberg** [comment]
Joo, niin menee mobiilinäkymässä esim, en ennättänyt korjata vielä. Jos
joku ennättää ensin niin pull requestia vaan :)
